// Requesting Open Questions
export const BRANCH_REQ_QUESTIONS_R = '[BRANCH]: REQ_QUESTIONS_R'
export const BRANCH_REQ_QUESTIONS_S = '[BRANCH]: REQ_QUESTIONS_S'
export const BRANCH_REQ_QUESTIONS_E = '[BRANCH]: REQ_QUESTIONS_E'

// Requesting Open Answers
export const BRANCH_REQ_AOPEN_R = '[BRANCH]: REQ_AOPEN_R'
export const BRANCH_REQ_AOPEN_S = '[BRANCH]: REQ_AOPEN_S'
export const BRANCH_REQ_AOPEN_E = '[BRANCH]: REQ_AOPEN_E'

// Requesting Close Answers
export const BRANCH_REQ_ACLOSE_R = '[BRANCH]: REQ_ACLOSE_R'
export const BRANCH_REQ_ACLOSE_S = '[BRANCH]: REQ_ACLOSE_S'
export const BRANCH_REQ_ACLOSE_E = '[BRANCH]: REQ_ACLOSE_E'

// Requesting KPIS
export const BRANCH_REQ_KPI_R = '[BRANCH]: REQ_KPI_R'
export const BRANCH_REQ_KPI_S = '[BRANCH]: REQ_KPI_S'
export const BRANCH_REQ_KPI_E = '[BRANCH]: REQ_KPI_E'

// Requesting STAFF
export const BRANCH_REQ_STAFF_RANKING_R = '[BRANCH]: REQ_STAFF_RANKING_R'
export const BRANCH_REQ_STAFF_RANKING_S = '[BRANCH]: REQ_STAFF_RANKING_S'
export const BRANCH_REQ_STAFF_RANKING_E = '[BRANCH]: REQ_STAFF_RANKING_E'

// Requesting HISTORIC
export const BRANCH_REQ_HISTORIC_R = '[BRANCH]: REQ_HISTORIC_R'
export const BRANCH_REQ_HISTORIC_S = '[BRANCH]: REQ_HISTORIC_S'
export const BRANCH_REQ_HISTORIC_E = '[BRANCH]: REQ_HISTORIC_E'

// Resets & Saves
export const BRANCH_RESET_ALL = '[BRANCH]: RESET_ALL'
export const BRANCH_RESET_BUT_INFO = '[BRANCH]: RESET_BUT_INFO'
export const BRANCH_INFO_SAVE = '[BRANCH]: INFO_SAVE'

// Filters and Queries
export const BRANCH_APPLY_CURRENT_QUERY = '[BRANCH]: APPLY_CURRENT_QUERY'
export const BRANCH_SAVE_CURRENT_QUERY = '[BRANCH]: SAVE_CURRENT_QUERY'
