// Requesting Open Questions
export const BRANCH_REQ_QOPEN_R = '[BRANCH]: REQ_QOPEN_R'
export const BRANCH_REQ_QOPEN_S = '[BRANCH]: REQ_QOPEN_S'
export const BRANCH_REQ_QOPEN_E = '[BRANCH]: REQ_QOPEN_E'

// Requesting Close Questions
export const BRANCH_REQ_QCLOSE_R = '[BRANCH]: REQ_QCLOSE_R'
export const BRANCH_REQ_QCLOSE_S = '[BRANCH]: REQ_QCLOSE_S'
export const BRANCH_REQ_QCLOSE_E = '[BRANCH]: REQ_QCLOSE_E'

// Requesting Open Answers
export const BRANCH_REQ_AOPEN_R = '[BRANCH]: REQ_AOPEN_R'
export const BRANCH_REQ_AOPEN_S = '[BRANCH]: REQ_AOPEN_S'
export const BRANCH_REQ_AOPEN_E = '[BRANCH]: REQ_AOPEN_E'

// Requesting Close Answers
export const BRANCH_REQ_ACLOSE_R = '[BRANCH]: REQ_ACLOSE_R'
export const BRANCH_REQ_ACLOSE_S = '[BRANCH]: REQ_ACLOSE_S'
export const BRANCH_REQ_ACLOSE_E = '[BRANCH]: REQ_ACLOSE_E'

// Requesting KPIS
export const BRANCH_REQ_KPI_R = '[BRANCH]: REQ_KPI_R'
export const BRANCH_REQ_KPI_S = '[BRANCH]: REQ_KPI_S'
export const BRANCH_REQ_KPI_E = '[BRANCH]: REQ_KPI_E'

// Requesting STAFF
export const BRANCH_REQ_STAFF_RANKING_R = '[BRANCH]: REQ_STAFF_RANKING_R'
export const BRANCH_REQ_STAFF_RANKING_S = '[BRANCH]: REQ_STAFF_RANKING_S'
export const BRANCH_REQ_STAFF_RANKING_E = '[BRANCH]: REQ_STAFF_RANKING_E'

// Requesting HISTORIC
export const BRANCH_REQ_HISTORIC_R = '[BRANCH]: REQ_HISTORIC_R'
export const BRANCH_REQ_HISTORIC_S = '[BRANCH]: REQ_HISTORIC_S'
export const BRANCH_REQ_HISTORIC_E = '[BRANCH]: REQ_HISTORIC_E'

// Charts Actions
export const BRANCH_CHARTS_OPEN_SAVE = '[BRANCH]: CHARTS_OPEN_SAVE'
export const BRANCH_CHARTS_KPIS_SAVE = '[BRANCH]: CHARTS_KPIS_SAVE'
export const BRANCH_CHARTS_HISTORIC_SAVE = '[BRANCH]: CHARTS_HISTORIC_SAVE'

// Resets
export const BRANCH_RESET_ALL = '[BRANCH]: RESET_ALL'
export const BRANCH_RESET_QA = '[BRANCH]: RESET_QA'
export const BRANCH_RESET_KPIS = '[BRANCH]: RESET_KPIS'

